###########################################################################
## Function to display GSEA plot 
## Modified to annotate new features on the plot 
###########################################################################

library(RColorBrewer)
library(ggplot2)
library(cowplot)
library(gridExtra)
library(ggpmisc)
library(colorspace)
library(grid)

##' @rdname gseaplot
##' @exportMethod gseaplot
setMethod("gseaplot", signature(x = "gseaResult"),
          function (x, geneSetID, by = "all", title = "", color='black',
                    color.line="green", color.vline="#FA5860", ...){
            gseaplot.gseaResult(x, geneSetID = geneSetID,
                                by = by, title = title,
                                color = color, color.line = color.line,
                                color.vline = color.vline, ...)
          })

##' @rdname gseaplot
##' @param color color of line segments
##' @param color.line color of running enrichment score line
##' @param color.vline color of vertical line which indicating the
##' maximum/minimal running enrichment score
##' @return ggplot2 object
##' @importFrom ggplot2 ggplot
##' @importFrom ggplot2 geom_linerange
##' @importFrom ggplot2 geom_line
##' @importFrom ggplot2 geom_vline
##' @importFrom ggplot2 geom_hline
##' @importFrom ggplot2 xlab
##' @importFrom ggplot2 ylab
##' @importFrom ggplot2 xlim
##' @importFrom ggplot2 aes
##' @importFrom ggplot2 ggplotGrob
##' @importFrom ggplot2 geom_segment
##' @importFrom ggplot2 ggplot_gtable
##' @importFrom ggplot2 ggplot_build
##' @importFrom ggplot2 ggtitle
##' @importFrom ggplot2 element_text
##' @importFrom ggplot2 rel
##' @importFrom cowplot plot_grid
##' @author Guangchuang Yu
gseaplot.gseaResult <- function (x, geneSetID, by = "all", title = "",
                                 color='black', color.line="green",
                                 color.vline="#FA5860", ...){
  by <- match.arg(by, c("runningScore", "preranked", "all"))
  gsdata <- gsInfo(x, geneSetID)
  p <- ggplot(gsdata, aes_(x = ~x)) +
    theme_dose() + xlab("Position in the Ranked List of Genes")
  if (by == "runningScore" || by == "all") {
    p.res <- p + geom_linerange(aes_(ymin=~ymin, ymax=~ymax), color=color)
    p.res <- p.res + geom_line(aes_(y = ~runningScore), color=color.line,
                               size=1)
    enrichmentScore <- x@result[geneSetID, "enrichmentScore"]
    es.df <- data.frame(es = which.min(abs(p$data$runningScore - enrichmentScore)))
    p.res <- p.res + geom_vline(data = es.df, aes_(xintercept = ~es),
                                colour = color.vline, linetype = "dashed")
    p.res <- p.res + ylab("Running Enrichment Score")
    p.res <- p.res + geom_hline(yintercept = 0)
  }
  if (by == "preranked" || by == "all") {
    df2 <- data.frame(x = which(p$data$position == 1))
    df2$y <- p$data$geneList[df2$x]
    p.pos <- p + geom_segment(data=df2, aes_(x=~x, xend=~x, y=~y, yend=0),
                              color=color)
    p.pos <- p.pos + ylab("Ranked List Metric") +
      xlim(0, length(p$data$geneList))
  }
  if (by == "runningScore")
    return(p.res + ggtitle(title))
  if (by == "preranked")
    return(p.pos + ggtitle(title))
  
  p.pos <- p.pos + xlab(NULL) + theme(axis.text.x = element_blank(),
                                      axis.ticks.x = element_blank())
  p.pos <- p.pos + ggtitle(title) +
    theme(plot.title=element_text(hjust=0.5, size=rel(2)))
  plot_grid(p.pos, p.res, ncol=1, align="v")
}


##' extract gsea result of selected geneSet
##'
##'
##' @title gsInfo
##' @param object gseaResult object
##' @param geneSetID gene set ID
##' @return data.frame
##' @author Guangchuang Yu
## @export
gsInfo <- function(object, geneSetID) {
  geneList <- object@geneList
  
  if (is.numeric(geneSetID))
    geneSetID <- object@result[geneSetID, "ID"]
  
  geneSet <- object@geneSets[[geneSetID]]
  exponent <- object@params[["exponent"]]
  df <- gseaScores(geneList, geneSet, exponent, fortify=TRUE)
  df$ymin <- 0
  df$ymax <- 0
  pos <- df$position == 1
  h <- diff(range(df$runningScore))/20
  df$ymin[pos] <- -h
  df$ymax[pos] <- h
  df$geneList <- geneList
  
  df$Description <- object@result[geneSetID, "Description"]
  return(df)
}

gseaScores <- getFromNamespace("gseaScores", "DOSE")




##' GSEA plot that mimic the plot generated by broad institute's GSEA software
##'
##'
##' @title gseaplot2
##' @param x gseaResult object
##' @param geneSetID gene set ID
##' @param title plot title
##' @param color color of running enrichment score line
##' @param base_size base font size
##' @param rel_heights relative heights of subplots
##' @param subplots which subplots to be displayed
##' @param pvalue_table whether add pvalue table
##' @param ES_geom geom for plotting running enrichment score,
##' one of 'line' or 'dot'
##' @return plot
##' @export
##' @importFrom ggplot2 theme_classic
##' @importFrom ggplot2 element_line
##' @importFrom ggplot2 element_text
##' @importFrom ggplot2 element_blank
##' @importFrom ggplot2 element_rect
##' @importFrom ggplot2 scale_x_continuous
##' @importFrom ggplot2 scale_y_continuous
##' @importFrom ggplot2 scale_color_manual
##' @importFrom ggplot2 theme_void
##' @importFrom ggplot2 geom_rect
##' @importFrom ggplot2 margin
##' @importFrom ggplot2 annotation_custom
##' @importFrom stats quantile
##' @importFrom RColorBrewer brewer.pal
##' @author Guangchuang Yu
mygseaplot2 <- function(x, geneSetID, title = "", color="green", base_size = 11,
                      rel_heights=c(1.5, .5, 1), subplots = 1:3,
                      pvalue_table = FALSE, ES_geom="line",res_table=FALSE, 
                      color_code = FALSE, show_core = TRUE) {
  ES_geom <- match.arg(ES_geom, c("line", "dot"))
  
  len_geneSetID <- length(geneSetID)
  geneList <- position <- NULL ## to satisfy codetool
  if (length(geneSetID) == 1) {
    gsdata <- gsInfo(x, geneSetID)
    color <- "green"
  } else {
    color <- qualitative_hcl(len_geneSetID,"Dark3")
    gsdata <- do.call(rbind, lapply(geneSetID, gsInfo, object = x))
    
  }
  p <- ggplot(gsdata, aes_(x = ~x)) + xlab(NULL) +
    theme_classic(base_size) +
    theme(panel.grid.major = element_line(colour = "grey92"),
          panel.grid.minor = element_line(colour = "grey92"),
          panel.grid.major.y = element_blank(),
          panel.grid.minor.y = element_blank()) +
    scale_x_continuous(expand=c(0,0))
  
  if (ES_geom == "line") {
    es_layer <- geom_line(aes_(y = ~runningScore, color= ~Description),
                          size=1)
  } else {
    es_layer <- geom_point(aes_(y = ~runningScore, color= ~Description),
                           size=1, data = subset(gsdata, position == 1))
  }
  
  p.res <- p + es_layer +
    theme(legend.position = c(.6, .8), legend.title = element_blank(),
          legend.background = element_rect(fill = "transparent"))
  
  p.res <- p.res + ylab("Running Enrichment Score") +
    geom_hline(yintercept=0, linetype="dashed", color = "red")+
    theme(axis.text.x=element_blank(),
          axis.ticks.x=element_blank(),
          axis.line.x=element_blank(),
          plot.margin=margin(t=.2, r = .2, b=0, l=.2, unit="cm"))
  
  
 
  
  
  
  
  if (show_core){
  ES <- x$enrichmentScore
  absolute_max <- gsdata[,1][which.max(abs(gsdata[,2]))]
  p.res <- p.res + geom_segment(aes(x = absolute_max, y = 0, 
                                    xend = absolute_max, yend = ES),
                                linetype="dashed", col = "seagreen",
                                size=1.2)
  }
  
  i <- 0
  for (term in unique(gsdata$Description)) {
    idx <- which(gsdata$ymin != 0 & gsdata$Description == term)
    gsdata[idx, "ymin"] <- i
    gsdata[idx, "ymax"] <- i + 1
    i <- i + 1
  }
 
  
  
  if (show_core){
    ## define colors of core targets
  ind_targets <- which(gsdata[,3] == 1)
  l <- length(ind_targets)
  
  if (ES < 0){
    ind_core <- ind_targets[which(ind_targets >= absolute_max)]
  } else {
    ind_core <- ind_targets[which(ind_targets <= absolute_max)]
  }
 
  vec_colors <- rep('blue', dim(gsdata)[1])
  gsdata <- cbind(gsdata, vec_colors)
  gsdata$vec_colors[ind_targets] <- 'black' 
  gsdata$vec_colors[ind_core] <- 'red'  
  
  p2 <- ggplot(gsdata, aes_(x = ~x)) +
    geom_linerange(aes_(ymin=~ymin, ymax=~ymax, color=~vec_colors)) +
    scale_color_manual(values = c("black","blue","red")) +
    xlab(NULL) + ylab(NULL) + theme_classic(base_size) +
    theme(legend.position = "none",
          plot.margin = margin(t=-.1, b=0,unit="cm"),
          axis.ticks = element_blank(),
          axis.text = element_blank(),
          axis.line.x = element_blank()) +
    scale_x_continuous(expand=c(0,0)) +
    scale_y_continuous(expand=c(0,0))
  } else {
    p2 <- ggplot(gsdata, aes_(x = ~x)) +
      geom_linerange(aes_(ymin=~ymin, ymax=~ymax, color=~Description)) +
      xlab(NULL) + ylab(NULL) + theme_classic(base_size) +
      theme(legend.position = "none",
            plot.margin = margin(t=-.1, b=0,unit="cm"),
            axis.ticks = element_blank(),
            axis.text = element_blank(),
            axis.line.x = element_blank()) +
      scale_x_continuous(expand=c(0,0)) +
      scale_y_continuous(expand=c(0,0))
  }
  
  
  
  if (length(geneSetID) == 1) {
    ## geneList <- gsdata$geneList
    ## j <- which.min(abs(geneList))
    ## v1 <- quantile(geneList[1:j], seq(0,1, length.out=6))[1:5]
    ## v2 <- quantile(geneList[j:length(geneList)], seq(0,1, length.out=6))[1:5]
    
    ## v <- sort(c(v1, v2))
    ## inv <- findInterval(geneList, v)
    
    v <- seq(1, sum(gsdata$position), length.out=9)
    inv <- findInterval(rev(cumsum(gsdata$position)), v)
    if (min(inv) == 0) inv <- inv + 1
    
    col <- c(rev(brewer.pal(5, "Blues")), brewer.pal(5, "Reds"))
    
    ymin <- min(p2$data$ymin)
    yy <- max(p2$data$ymax - p2$data$ymin) * .3
    xmin <- which(!duplicated(inv))
    xmax <- xmin + as.numeric(table(inv)[as.character(unique(inv))])
    d <- data.frame(ymin = ymin, ymax = yy,
                    xmin = xmin,
                    xmax = xmax,
                    col = col[unique(inv)])
    
    if(color_code){
    p2 <- p2 + geom_rect(
      aes_(xmin=~xmin,
           xmax=~xmax,
           ymin=~ymin,
           ymax=~ymax,
           fill=~I(col)),
      data=d,
      alpha=.9,
      inherit.aes=FALSE)
    }
  }
  
  ## p2 <- p2 +
  ## geom_rect(aes(xmin=x-.5, xmax=x+.5, fill=geneList),
  ##           ymin=ymin, ymax = ymin + yy, alpha=.5) +
  ## theme(legend.position="none") +
  ## scale_fill_gradientn(colors=color_palette(c("blue", "red")))
  
  df2 <- p$data #data.frame(x = which(p$data$position == 1))
  df2$y <- p$data$geneList[df2$x]
  length_list <- length(x@geneList)
  p.pos <- p + geom_segment(data=df2, aes_(x=~x, xend=~x, y=~y, yend=0),
                            color="grey")
  p.pos <- p.pos + ylab("Ranked List Metric") +
    xlab("Rank in Ordered Dataset") +
    theme(plot.margin=margin(t = -.1, r = .2, b=.2, l=.2, unit="cm"))
  # p.pos <- p.pos + annotate("text", x=(length_list - 1500)  ,y=max(df2$y), 
  #                            label ='Negative', col = 'blue',  size=10)
  # p.pos <- p.pos + annotate("text", x=1500  ,y=max(df2$y), 
  #                           label ='Positive', col = 'red', size=10)
  # p.pos <- p.pos + geom_segment(aes(x = 1500, y = max(df2$y), xend = 0.01, 
  #                    yend = max(df2$y)), col = 'red',
  #                  arrow = arrow(length = unit(0.1, "inches")))
  # 
  # p.pos <- p.pos + geom_segment(aes(x=(length_list - 1500), 
  #                                   y = max(df2$y), xend = length_list, 
  #                                   yend = max(df2$y) ), col = 'blue',
  #                               arrow = arrow(length = unit(0.1, "inches")))

  
  if (!is.null(title) && !is.na(title) && title != "")
    p.res <- p.res + ggtitle(title)
  
  if (length(color) == length(geneSetID)) {
    p.res <- p.res + scale_color_manual(values=color)
    if (length(color) == 1) {
      p.res <- p.res + theme(legend.position = "none")
      ##p2 <- p2 + scale_color_manual(values = "black")
    } else {
      p2 <- p2 + scale_color_manual(values = color)
    }
  }
  
  if (pvalue_table) {
    pd <- x[geneSetID, c("Description", "pvalue", "p.adjust")]
    #pd <- pd[order(pd[,1], decreasing=FALSE),]
    rownames(pd) <- pd$Description
    
    pd <- pd[,-1]
    pd <- round(pd, 4)
    
    tp <- tableGrob2(pd, p.res)
    
    p.res <- p.res + theme(legend.position = "none") +
      annotation_custom(tp,
                        xmin = quantile(p.res$data$x, .5),
                        xmax = quantile(p.res$data$x, .95),
                        ymin = quantile(p.res$data$runningScore, .75),
                        ymax = quantile(p.res$data$runningScore, .9))
  } else if (length(geneSetID) == 1){
    
    p.res <- p.res+annotate("text", x=(length(x@geneList) - 1500)  ,y=0.05, 
                            label =paste('p-value =', signif(x@result[["pvalue"]], digits=2)))
  } 
  
  
  
  
  if (res_table){
    # recuperation des vecteurs avec les resultats
    vec_Thr <- c()
    for (i in x@result[["ID"]]){
      separation <- strsplit(i,'_')
      ID <-separation[[1]][2]
      vec_Thr <- c(vec_Thr,ID)
    }
    
    `Nb targets`<-c()
    for (i in x@geneSets){
      nb_targets <- length(which(i %in% names(x@geneList)))
      `Nb targets`<-c(`Nb targets`,nb_targets)
    }
    
    order_res <- order(-(as.numeric(vec_Thr)))
    
    `ES`<- signif(x@result[["enrichmentScore"]],digits=2)[order_res]
    `p-value`<- signif(x@result[["pvalue"]],digits=2)[order_res]
    `Thr` <- vec_Thr[order_res]
    
    my_table <- tableGrob(as.matrix(t(rbind(`Thr`,`Nb targets`,`ES`,`p-value`))))
    
    # rows coloration 
    
    
    max=(len_geneSetID +2)*4
    min=(2*4+1)
    vec_color <- rep(color,4)
    vec_inds <- c(min:max)
    
    my_table<- modify_cells(my_table, c(1:4), gpar(fontsize=9))
    my_table<- modify_cells_colors(my_table, vec_inds, vec_color)
    
    
    if(sum(`ES`)<0){
      p.res <- p.res+ theme(legend.position = "none") +
        annotation_custom(my_table,
                          xmin = quantile(p.res$data$x, .05),
                          xmax = quantile(p.res$data$x, .3),
                          ymin = quantile(p.res$data$runningScore, .4),
                          ymax = quantile(p.res$data$runningScore, .4))
    }else{
    
    p.res <- p.res+ theme(legend.position = "none") +
      annotation_custom(my_table,
                        xmin = quantile(p.res$data$x, .7),
                        xmax = quantile(p.res$data$x, .9),
                        ymin = quantile(p.res$data$runningScore, .75),
                        ymax = quantile(p.res$data$runningScore, .9))
    }
      # annotate(geom = "table", x = 2000, 
      #                        y = -0.05, label = list(my_table), 
      #        vjust = 1, hjust = 0)
  }
  
  plotlist <- list(p.res, p2, p.pos)[subplots]
  n <- length(plotlist)
  plotlist[[n]] <- plotlist[[n]] +
    theme(axis.line.x = element_line(),
          axis.ticks.x=element_line(),
          axis.text.x = element_text())
  
  if (length(subplots) == 1)
    return(plotlist[[1]] + theme(plot.margin=margin(t=.2, r = .2, b=.2,
                                                    l=.2, unit="cm")))
  
  
  if (length(rel_heights) > length(subplots))
    rel_heights <- rel_heights[subplots]
  
  plot_grid(plotlist = plotlist, ncol=1, align="v", rel_heights=rel_heights)
}


##' plot ranked list of genes with running enrichment score as bar height
##'
##'
##' @title gsearank
##' @param x gseaResult object
##' @param geneSetID gene set ID
##' @param title plot title
##' @return ggplot object
##' @importFrom ggplot2 geom_segment
##' @importFrom ggplot2 theme_minimal
##' @export
##' @author Guangchuang Yu
gsearank <- function(x, geneSetID, title="") {
  position <- NULL
  gsdata <- gsInfo(x, geneSetID)
  gsdata <- subset(gsdata, position == 1)
  p <- ggplot(gsdata, aes_(x = ~x, y = ~runningScore)) +
    geom_segment(aes_(xend=~x, yend=0)) +
    ggtitle(title) +
    xlab("Position in the Ranked List of Genes") +
    ylab("Running Enrichment Score") +
    theme_minimal()
  return(p)
}

##
##
##
##
## Functions for grid table display parameters
modify_cells_colors <- function(g, ids, coloris){
  for (x in 1:length(ids)){
    g$grobs[ids[x]][[1]][["gp"]] <- gpar(col=coloris[x],fontsize=12)
  }
  return(g)
}

modify_cells <- function(g, ids, gp=gpar()){
  for(id in ids) g$grobs[id][[1]][["gp"]] <- gp
  return(g)
}

##
##
##
##
## Function to build the result table
# recuperation des vecteurs avec les resultats
build_res_table <- function(res,geneSetID){

len_geneSetID <- length(geneSetID)
color <- qualitative_hcl(len_geneSetID,"Dark3")


  
vec_Thr <- c()
for (i in res@result[["ID"]]){
  separation <- strsplit(i,'_')
  ID <-separation[[1]][2]
  vec_Thr <- c(vec_Thr,ID)
}

`Nb targets`<-c()
for (i in res@geneSets){
  nb_targets <- length(which(i %in% names(res@geneList)))
  `Nb targets`<-c(`Nb targets`,nb_targets)
}

order_res <- order(-(as.numeric(vec_Thr)))

`ES`<- signif(res@result[["enrichmentScore"]],digits=2)[order_res]
`p-value`<- signif(res@result[["pvalue"]],digits=2)[order_res]
`Thr` <- vec_Thr[order_res]

my_table <- tableGrob(as.matrix(t(rbind(`Thr`,`Nb targets`,`ES`,`p-value`))))

# rows coloration 


max=(len_geneSetID +2)*4
min=(2*4+1)
vec_color <- rep(color,4)
vec_inds <- c(min:max)

my_table<- modify_cells(my_table, c(1:4), gpar(fontsize=9))
my_table<- modify_cells_colors(my_table, vec_inds, vec_color)


grid.draw(my_table)

}
